module.exports = {
    NODE_ENV: process.env.NODE_ENV || 'local',
    EXPRESS_PORT: process.env.EXPRESS_PORT || '9090',
    BC_NODE_URL: process.env.BC_NODE_URL,
    BC_TAB_REGISTRY_CONTRACT: process.env.BC_TAB_REGISTRY_CONTRACT,
    BC_PRICE_ORACLE_MANAGER_CONTRACT: process.env.BC_PRICE_ORACLE_MANAGER_CONTRACT,
    BC_PRICE_ORACLE_CONTRACT: process.env.BC_PRICE_ORACLE_CONTRACT,
    BC_CONFIG_CONTRACT: process.env.BC_CONFIG_CONTRACT,
    BC_VAULT_MANAGER_CONTRACT: process.env.BC_VAULT_MANAGER_CONTRACT,
    BC_PRICE_ORACLE_PRIVATE_KEY: process.env.BC_PRICE_ORACLE_PRIVATE_KEY,
    BC_KEEPER_PRIVATE_KEY: process.env.BC_KEEPER_PRIVATE_KEY,
    DB_URL: process.env.DB_URL,
    NFT_STORAGE_API_KEY: process.env.NFT_STORAGE_API_KEY,
    CURR_DETAILS: {
        CURR_DETAILS_URL1: process.env.CURR_DETAILS_URL1,
        CURR_DETAILS_URL2: process.env.CURR_DETAILS_URL2,
        CURR_DETAILS_URL3: process.env.CURR_DETAILS_URL3,
        CURR_DETAILS_URL3_APIKEY: process.env.CURR_DETAILS_URL3_APIKEY
    },
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_IV: process.env.AUTH_IV || 'shiftCtrl_DEV_v1',
    PRIVATE_TOKEN: process.env.PRIVATE_TOKEN || '73686966744374726c5f5052445f7631:b2773dc62f5365dbb0e4ae289374dfddfe80dcaf419ba987a5ce3c69b99da0e994c6046918431ac43d09bd886b972926'
};